name: Process Merged PR

on:
  pull_request:
    types: [closed]

jobs:
  process-pr:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run PR Processor
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_NAME: "user_backend"
          PROLOG_URL: "http://50.17.253.228:5000/add"
        run: python add_changelog.py

